
 node('master')
{
    stage('count downlhd')
{
    git 'https://github.com/dileepchiru/dddd.git'
}
stage('count build')
{
 sh label: '', script: 'mvn package'   
}
stage('count depoly')
{
    sh label: '', script: 'scp /home/ubuntu/.jenkins/workspace/scriptedpipeline/webapp/target/webapp.war ubuntu@172.31.16.96:/var/lib/tomcat7/webapps/qa.war'
}
stage ('count testing')
{
    git'https://github.com/selenium-saikrishna/TestingNew.git'
}
stage('count delivery')
{
    input message:'waiting for approval from delivery manager!',submitter:'dileep'
    sh label: '', script: 'scp /home/ubuntu/.jenkins/workspace/scriptedpipeline/webapp/target/webapp.war ubuntu@172.31.24.58:/var/lib/tomcat7/webapps/prod.war' 
}
}
